# 추가 Swagger 예제들

# 홈페이지 API 문서화
home_response_example:
  user:
    name: "김테니스"
    greeting: "좋은 아침이에요"
    motivationMessage: "오늘도 화이팅!"
  upcomingMatches:
    - id: "550e8400-e29b-41d4-a716-446655440201"
      title: "즐거운 주말 복식"
      location: "올림픽공원 테니스장"
      court: "1번 코트"
      date: "01/15"
      startTime: "14:00"
      endTime: "16:00"
      participants: "3/4"
      gameType: "복식"
      level: "초중급"
      price: "20,000원"
      status: "recruiting"
      hostName: "김테니스"
      description: "즐거운 주말 복식 경기입니다"

# 매치 상세 정보 예제
match_detail_example:
  id: "550e8400-e29b-41d4-a716-446655440201"
  title: "즐거운 주말 단식 매치"
  location: "올림픽공원 테니스장"
  court: "1번 코트"
  address: "서울특별시 송파구 올림픽로 424"
  date: "01/15"
  startTime: "14:00"
  endTime: "16:00"
  participants: "2/2"
  gameType: "단식"
  level: "중급"
  price: "20,000원"
  status: "full"
  hostName: "김테니스"
  hostNtrp: "4.0"
  hostExperience: "3년"
  description: "즐겁고 건전한 테니스 경기를 하실 분을 모집합니다!"
  rules:
    - "매너를 지켜주세요"
    - "시간을 꼭 지켜주세요"
    - "안전사고 주의해주세요"
  equipment:
    - "라켓"
    - "테니스공"
    - "수건"
  parking: "2시간 무료주차 가능"
  amenities:
    - "샤워실"
    - "락커"
    - "매점"
    - "휴게실"
  confirmedParticipants:
    - id: "550e8400-e29b-41d4-a716-446655440501"
      name: "김테니스"
      ntrp: "4.0"
      experience: "3년"
      isHost: true

# 지역 데이터 예제
regions_example:
  regions:
    서울시:
      type: "city"
      districts:
        - "강남구"
        - "서초구"
        - "송파구"
    경기도:
      type: "province"
      districts:
        수원시:
          - "영통구"
          - "장안구"
          - "권선구"
          - "팔달구"
        성남시:
          - "분당구"
          - "중원구"
          - "수정구"

# 테니스장 검색 예제
venues_example:
  venues:
    - id: "550e8400-e29b-41d4-a716-446655440101"
      name: "올림픽공원 테니스장"
      address: "서울특별시 송파구 올림픽로 424"
      courts:
        - "1번 코트"
        - "2번 코트"
        - "3번 코트"
      amenities:
        - "주차장"
        - "샤워실"
        - "락커"
      priceRange: "15,000-25,000원"